# Generated by pipedat: do not edit by hand
# This file defines the pipeline for the ResearchCompendium project.
library(targets)
library(tarchetypes)
library(pipedat) # To remove by the end of the project

tar_option_set(packages = c('curl', 'googleCloudStorageR', 'aws.s3', 'yaml', 'dplyr'), format = 'file') # To edit properly by the end of the project

tar_source('workspace/scripts/') # To edit properly by the end of the project
list(
  tar_target(bibtex_master, bibtex_master(), format = "file", cue = tar_cue(mode = "always")),
    list(tarchetypes::tar_download(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Event_Information, 
    url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_90c40dba-740d-473b-8489-1c4eb3331555/piei_event_information_estuary_gulf_2017-2021.csv", 
    path = "workspace/data/harvested/biodiversite_piei-1.0.0/raw/piei_event_information_estuary_gulf_2017-2021.csv"), 
    tarchetypes::tar_download(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Taxon_Occurrences, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_90c40dba-740d-473b-8489-1c4eb3331555/piei_taxon_occurrence_estuary_gulf_2017-2021.csv", 
        path = "workspace/data/harvested/biodiversite_piei-1.0.0/raw/piei_taxon_occurrence_estuary_gulf_2017-2021.csv"), 
    tarchetypes::tar_download(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Visual_Dictionary__EN_, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_90c40dba-740d-473b-8489-1c4eb3331555/Dic_visuel_ISM_MPO_PIEI_20220310_EN.pdf", 
        path = "workspace/data/harvested/biodiversite_piei-1.0.0/raw/Dic_visuel_ISM_MPO_PIEI_20220310_EN.pdf"), 
    tarchetypes::tar_download(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Visual_Dictionary__FR_, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_90c40dba-740d-473b-8489-1c4eb3331555/Dic_visuel_ISM_MPO_PIEI_20220310_FR.pdf", 
        path = "workspace/data/harvested/biodiversite_piei-1.0.0/raw/Dic_visuel_ISM_MPO_PIEI_20220310_FR.pdf"), 
    tar_target(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_process_biodiversite_piei, 
        {
            prc_biodiversite_piei(output_path = "workspace/data/harvested/biodiversite_piei-1.0.0/processed", 
                input_files = list(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Event_Information, 
                  tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Taxon_Occurrences))
            c("workspace/data/harvested/biodiversite_piei-1.0.0/processed/events_piei.csv", 
            "workspace/data/harvested/biodiversite_piei-1.0.0/processed/occurrences_piei.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_Event_Data, 
    url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_e234a1a5-e21e-4c09-bc77-d92d72796ae7/kelp_event-data_2018-2019.csv", 
    path = "workspace/data/harvested/inventaire_batture_alouettes-1.0.0/raw/kelp_event-data_2018-2019.csv"), 
    tarchetypes::tar_download(tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_Occurrence_Data, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_e234a1a5-e21e-4c09-bc77-d92d72796ae7/kelp_occurrence-data_2018-2019.csv", 
        path = "workspace/data/harvested/inventaire_batture_alouettes-1.0.0/raw/kelp_occurrence-data_2018-2019.csv"), 
    tar_target(tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_process_inventaire_batture_alouettes, 
        {
            prc_inventaire_batture_alouettes(output_path = "workspace/data/harvested/inventaire_batture_alouettes-1.0.0/processed", 
                input_files = list(tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_Event_Data, 
                  tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_Occurrence_Data))
            c("workspace/data/harvested/inventaire_batture_alouettes-1.0.0/processed/kelp_events.csv", 
            "workspace/data/harvested/inventaire_batture_alouettes-1.0.0/processed/kelp_occurrences.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Evenements_echantillonnage, 
    url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_4bb77d86-b94e-4f61-b91b-fdcfd6ecbaed/macroalgae-macroinvertebrates_event-data_2019.csv", 
    path = "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/raw/macroalgae-macroinvertebrates_event-data_2019.csv"), 
    tarchetypes::tar_download(tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Occurrences_macroinvertebres, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_4bb77d86-b94e-4f61-b91b-fdcfd6ecbaed/macroalgae-macroinvertebrates_occurrence-data_2019.csv", 
        path = "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/raw/macroalgae-macroinvertebrates_occurrence-data_2019.csv"), 
    tarchetypes::tar_download(tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Mesures_abiotiques, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_4bb77d86-b94e-4f61-b91b-fdcfd6ecbaed/macroalgae-macroinvertebrates_abiotic-measurement_2019.csv", 
        path = "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/raw/macroalgae-macroinvertebrates_abiotic-measurement_2019.csv"), 
    tar_target(tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_process_inventaire_macroalgues_macroinvertebres, 
        {
            prc_inventaire_macroalgues_macroinvertebres(output_path = "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/processed", 
                input_files = list(tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Evenements_echantillonnage, 
                  tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Occurrences_macroinvertebres, 
                  tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Mesures_abiotiques))
            c("workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/processed/events.csv", 
            "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/processed/occurrences.csv", 
            "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/processed/abiotic.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Evenements_echantillonnage, 
    url = "https://catalogue.ogsl.ca/data/cegep-sherbrooke/ca-cioos_b943abc0-09be-43c6-a003-efa665a6c8a9/DwC_cegepSher_pointe-john_event_2021.csv", 
    path = "workspace/data/harvested/inventaire_pointe_john-1.0.0/raw/events_pointe_john.csv"), 
    tarchetypes::tar_download(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Mesures_physico_chimiques, 
        url = "https://catalogue.ogsl.ca/data/cegep-sherbrooke/ca-cioos_b943abc0-09be-43c6-a003-efa665a6c8a9/DwC_cegepSher_pointe-john_event-emof_2021.csv", 
        path = "workspace/data/harvested/inventaire_pointe_john-1.0.0/raw/physico_chem_pointe_john.csv"), 
    tarchetypes::tar_download(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Observations_taxons, 
        url = "https://catalogue.ogsl.ca/data/cegep-sherbrooke/ca-cioos_b943abc0-09be-43c6-a003-efa665a6c8a9/DwC_cegepSher_pointe-john_occurrence_2021.csv", 
        path = "workspace/data/harvested/inventaire_pointe_john-1.0.0/raw/occurrences_pointe_john.csv"), 
    tarchetypes::tar_download(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Recouvrement_especes, 
        url = "https://catalogue.ogsl.ca/data/cegep-sherbrooke/ca-cioos_b943abc0-09be-43c6-a003-efa665a6c8a9/DwC_cegepSher_pointe-john_occurrence-emof_2021.csv", 
        path = "workspace/data/harvested/inventaire_pointe_john-1.0.0/raw/species_recovery_pointe_john.csv"), 
    tar_target(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_processing_inventaire_pointe_john, 
        {
            prc_inventaire_pointe_john(output_path = "workspace/data/harvested/inventaire_pointe_john-1.0.0/processed", 
                input_files = list(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Evenements_echantillonnage, 
                  tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Mesures_physico_chimiques, 
                  tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Observations_taxons, 
                  tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Recouvrement_especes))
            c("workspace/data/harvested/inventaire_pointe_john-1.0.0/processed/events_pointe_john.csv", 
            "workspace/data/harvested/inventaire_pointe_john-1.0.0/processed/occurrences_pointe_john.csv", 
            "workspace/data/harvested/inventaire_pointe_john-1.0.0/processed/physico_chem_pointe_john.csv", 
            "workspace/data/harvested/inventaire_pointe_john-1.0.0/processed/species_recovery_pointe_john.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Evenements_echantillonnage, 
    url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_0756dd24-4bf4-47ab-a325-c83f9ed763da/DL_CPD_PPO_EVENT_Fr_20230830.csv", 
    path = "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/raw/evenements_cpd.csv"), 
    tarchetypes::tar_download(tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Occurrences, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_0756dd24-4bf4-47ab-a325-c83f9ed763da/DL_CPD_PPO_OCCURENCE_Fr_20230830.csv", 
        path = "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/raw/occurrences_cpd.csv"), 
    tarchetypes::tar_download(tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Dictionnaire_des_donnees, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_0756dd24-4bf4-47ab-a325-c83f9ed763da/DataDictionary_DictionnaireDonnees_MP_AR20230824.csv", 
        path = "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/raw/dictionnaire_donnees.csv"), 
    tar_target(tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_process_invertebres_vegetation_saint_laurent, 
        {
            prc_invertebres_vegetation_saint_laurent(output_path = "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/processed", 
                input_files = list(tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Evenements_echantillonnage, 
                  tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Occurrences, 
                  tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Dictionnaire_des_donnees))
            c("workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/processed/evenements_cpd.csv", 
            "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/processed/occurrences_cpd.csv", 
            "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/processed/dictionnaire_donnees.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Evenements_echantillonnage, 
    url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_event_2019-2021.csv", 
    path = "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/raw/marais_pointe_fortin_events.csv"), 
    tarchetypes::tar_download(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Mesures_abiotiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_event_emof_2019-2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/raw/marais_pointe_fortin_abiotic.csv"), 
    tarchetypes::tar_download(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Occurrences_biologiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_occurrence_2019-2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/raw/marais_pointe_fortin_occurrences.csv"), 
    tarchetypes::tar_download(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Donnees_abondance, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_occurrence_emof_2019-2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/raw/marais_pointe_fortin_abundance.csv"), 
    tar_target(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_process_zip_inventaire_marais_pointe_fortin, 
        {
            prc_zip_inventaire_marais_pointe_fortin(output_path = "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/processed", 
                input_files = list(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Evenements_echantillonnage, 
                  tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Mesures_abiotiques, 
                  tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Occurrences_biologiques, 
                  tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Donnees_abondance))
            c("workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/processed/marais_pointe_fortin_events.csv", 
            "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/processed/marais_pointe_fortin_abiotic.csv", 
            "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/processed/marais_pointe_fortin_occurrences.csv", 
            "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/processed/marais_pointe_fortin_abundance.csv"
            )
        }, format = "file"))
)
