# Generated by pipedat: do not edit by hand
# This file defines the pipeline for the ResearchCompendium project.
library(targets)
library(tarchetypes)
library(pipedat) # To remove by the end of the project

tar_option_set(packages = c('curl', 'googleCloudStorageR', 'aws.s3', 'yaml', 'dplyr'), format = 'file') # To edit properly by the end of the project

tar_source('workspace/scripts/') # To edit properly by the end of the project
list(
  tar_target(bibtex_master, bibtex_master(), format = "file", cue = tar_cue(mode = "always")),
    list(tarchetypes::tar_download(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Event_Information, 
    url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_90c40dba-740d-473b-8489-1c4eb3331555/piei_event_information_estuary_gulf_2017-2021.csv", 
    path = "workspace/data/harvested/biodiversite_piei-1.0.0/raw/piei_event_information_estuary_gulf_2017-2021.csv"), 
    tarchetypes::tar_download(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Taxon_Occurrences, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_90c40dba-740d-473b-8489-1c4eb3331555/piei_taxon_occurrence_estuary_gulf_2017-2021.csv", 
        path = "workspace/data/harvested/biodiversite_piei-1.0.0/raw/piei_taxon_occurrence_estuary_gulf_2017-2021.csv"), 
    tarchetypes::tar_download(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Visual_Dictionary__EN_, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_90c40dba-740d-473b-8489-1c4eb3331555/Dic_visuel_ISM_MPO_PIEI_20220310_EN.pdf", 
        path = "workspace/data/harvested/biodiversite_piei-1.0.0/raw/Dic_visuel_ISM_MPO_PIEI_20220310_EN.pdf"), 
    tarchetypes::tar_download(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Visual_Dictionary__FR_, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_90c40dba-740d-473b-8489-1c4eb3331555/Dic_visuel_ISM_MPO_PIEI_20220310_FR.pdf", 
        path = "workspace/data/harvested/biodiversite_piei-1.0.0/raw/Dic_visuel_ISM_MPO_PIEI_20220310_FR.pdf"), 
    tar_target(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_process_biodiversite_piei, 
        {
            prc_biodiversite_piei(output_path = "workspace/data/harvested/biodiversite_piei-1.0.0/processed", 
                input_files = list(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Event_Information, 
                  tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_Taxon_Occurrences))
            c("workspace/data/harvested/biodiversite_piei-1.0.0/processed/events_piei.csv", 
            "workspace/data/harvested/biodiversite_piei-1.0.0/processed/occurrences_piei.csv"
            )
        }, format = "file")),
    list(list(tar_target(tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "io_herbier_benthos/logbook/io_herbiers_benthos_2023.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_herbiers_benthos_2023.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_herbiers_benthos_2023.csv"
    }, format = "file")), list(tar_target(tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos_biodiversity_abondance, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "io_herbier_benthos/biodiversity/io_biodiversity_2023_abondance_m2.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_biodiversity_2023_abondance_m2.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_biodiversity_2023_abondance_m2.csv"
    }, format = "file")), list(tar_target(tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos_biodiversity_biomasse, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "io_herbier_benthos/biodiversity/io_biodiversity_2023_biomasse_m2.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_biodiversity_2023_biomasse_m2.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_biodiversity_2023_biomasse_m2.csv"
    }, format = "file")), list(tar_target(tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos_biodiversity_classification, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "io_herbier_benthos/biodiversity/io_biodiversity_2023_classification.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_biodiversity_2023_classification.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_biodiversity_2023_classification.csv"
    }, format = "file")), list(tar_target(tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos_biodiversity_presence, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "io_herbier_benthos/biodiversity/io_biodiversity_2023_presence.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_biodiversity_2023_presence.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_biodiversity_2023_presence.csv"
    }, format = "file")), list(tar_target(tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos_biodiversity_stations, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "io_herbier_benthos/biodiversity/io_biodiversity_2023_stations.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_biodiversity_2023_stations.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/raw/io_biodiversity_2023_stations.csv"
    }, format = "file")), tar_target(tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_processing_biome_io_herbier_benthos, 
    {
        prc_biome_io_herbier_benthos(output_path = "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/processed", 
            input_files = list(tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos, 
                tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos_biodiversity_abondance, 
                tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos_biodiversity_biomasse, 
                tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos_biodiversity_classification, 
                tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos_biodiversity_presence, 
                tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_io_herbier_benthos_biodiversity_stations))
        c("workspace/data/harvested/biome_io_herbier_benthos-1.0.0/processed/biome_io_herbier_benthos_logbooks.csv", 
        "workspace/data/harvested/biome_io_herbier_benthos-1.0.0/processed/biome_io_herbier_benthos_biodiversity.csv"
        )
    }, format = "file")),
    list(list(tar_target(tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_biodiversity_2021, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "lagrave/biodiversity/lg_biodiversity_2021.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_biodiversity_2021.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_biodiversity_2021.csv"
    }, format = "file")), list(tar_target(tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_biodiversity_2022, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "lagrave/biodiversity/lg_biodiversity_2022.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_biodiversity_2022.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_biodiversity_2022.csv"
    }, format = "file")), list(tar_target(tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_biodiversity_2023, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "lagrave/biodiversity/lg_biodiversity_2023.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_biodiversity_2023.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_biodiversity_2023.csv"
    }, format = "file")), list(tar_target(tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_logbook_2021, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "lagrave/logbook/lg_logbook_2021.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_logbook_2021.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_logbook_2021.csv"
    }, format = "file")), list(tar_target(tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_logbook_2022, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "lagrave/logbook/lg_logbook_2022.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_logbook_2022.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_logbook_2022.csv"
    }, format = "file")), list(tar_target(tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_logbook_2023, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "lagrave/logbook/lg_logbook_2023.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_logbook_2023.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_logbook_2023.csv"
    }, format = "file")), list(tar_target(tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_logbook_2024, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "lagrave/logbook/lg_logbook_2024.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_logbook_2024.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_lagrave-1.0.0/raw/lg_logbook_2024.csv"
    }, format = "file")), tar_target(tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_processing_biome_recharge_lagrave, 
    {
        prc_biome_recharge_lagrave(output_path = "workspace/data/harvested/biome_recharge_lagrave-1.0.0/processed", 
            input_files = list(tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_biodiversity_2021, 
                tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_biodiversity_2022, 
                tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_biodiversity_2023, 
                tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_logbook_2021, 
                tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_logbook_2022, 
                tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_logbook_2023, 
                tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_lagrave_logbook_2024))
        c("workspace/data/harvested/biome_recharge_lagrave-1.0.0/processed/biome_recharge_lagrave_logbooks.csv", 
        "workspace/data/harvested/biome_recharge_lagrave-1.0.0/processed/biome_recharge_lagrave_biodiversity.csv"
        )
    }, format = "file")),
    list(list(tar_target(tg_c6b58e09_2b7e_4f24_a1d1_3826acbf5840_maria_logbook_2024, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "maria/logbook/maria_logbook_2024.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_maria-1.0.0/raw/maria_logbook_2024.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_maria-1.0.0/raw/maria_logbook_2024.csv"
    }, format = "file")), tar_target(tg_c6b58e09_2b7e_4f24_a1d1_3826acbf5840_processing_biome_recharge_maria, 
    {
        prc_biome_recharge_maria(output_path = "workspace/data/harvested/biome_recharge_maria-1.0.0/processed", 
            input_files = list(tg_c6b58e09_2b7e_4f24_a1d1_3826acbf5840_maria_logbook_2024))
        "workspace/data/harvested/biome_recharge_maria-1.0.0/processed/biome_recharge_maria_logbooks.csv"
    }, format = "file")),
    list(list(tar_target(tg_e7c1ea73_41f3_4bf0_a5f0_16ad97416965_pointe_aux_loups_biodiversity_2023, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "pointe-aux-loups/biodiversity/pal_biodiversity_2023.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_pointe-aux-loups-1.0.0/raw/pal_biodiversity_2023.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_pointe-aux-loups-1.0.0/raw/pal_biodiversity_2023.csv"
    }, format = "file")), list(tar_target(tg_e7c1ea73_41f3_4bf0_a5f0_16ad97416965_pointe_aux_loups_logbook_2023, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "pointe-aux-loups/logbook/pal_logbook_2023.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_pointe-aux-loups-1.0.0/raw/pal_logbook_2023.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_pointe-aux-loups-1.0.0/raw/pal_logbook_2023.csv"
    }, format = "file")), list(tar_target(tg_e7c1ea73_41f3_4bf0_a5f0_16ad97416965_pointe_aux_loups_logbook_2024, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "pointe-aux-loups/logbook/pal_logbook_2024.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_pointe-aux-loups-1.0.0/raw/pal_logbook_2024.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_pointe-aux-loups-1.0.0/raw/pal_logbook_2024.csv"
    }, format = "file")), tar_target(tg_e7c1ea73_41f3_4bf0_a5f0_16ad97416965_processing_biome_recharge_pointe_aux_loups, 
    {
        prc_biome_recharge_pointe_aux_loups(output_path = "workspace/data/harvested/biome_recharge_pointe-aux-loups-1.0.0/processed", 
            input_files = list(tg_e7c1ea73_41f3_4bf0_a5f0_16ad97416965_pointe_aux_loups_biodiversity_2023, 
                tg_e7c1ea73_41f3_4bf0_a5f0_16ad97416965_pointe_aux_loups_logbook_2023, 
                tg_e7c1ea73_41f3_4bf0_a5f0_16ad97416965_pointe_aux_loups_logbook_2024))
        c("workspace/data/harvested/biome_recharge_pointe-aux-loups-1.0.0/processed/biome_recharge_pointe-aux-loups_logbooks.csv", 
        "workspace/data/harvested/biome_recharge_pointe-aux-loups-1.0.0/processed/biome_recharge_pointe-aux-loups_biodiversity.csv"
        )
    }, format = "file")),
    list(list(tar_target(tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_biodiversity_2021, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "pointe-aux-outardes/biodiversity/pao_biodiversity_2021.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_biodiversity_2021.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_biodiversity_2021.csv"
    }, format = "file")), list(tar_target(tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_biodiversity_2022, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "pointe-aux-outardes/biodiversity/pao_biodiversity_2022.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_biodiversity_2022.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_biodiversity_2022.csv"
    }, format = "file")), list(tar_target(tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_biodiversity_2023, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "pointe-aux-outardes/biodiversity/pao_biodiversity_2023.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_biodiversity_2023.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_biodiversity_2023.csv"
    }, format = "file")), list(tar_target(tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_logbook_2021, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "pointe-aux-outardes/logbook/pao_logbook_2021.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_logbook_2021.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_logbook_2021.csv"
    }, format = "file")), list(tar_target(tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_logbook_2022, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "pointe-aux-outardes/logbook/pao_logbook_2022.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_logbook_2022.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_logbook_2022.csv"
    }, format = "file")), list(tar_target(tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_logbook_2023, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "pointe-aux-outardes/logbook/pao_logbook_2023.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_logbook_2023.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_logbook_2023.csv"
    }, format = "file")), list(tar_target(tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_logbook_2024, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "pointe-aux-outardes/logbook/pao_logbook_2024.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_logbook_2024.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/raw/pao_logbook_2024.csv"
    }, format = "file")), tar_target(tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_processing_biome_recharge_pointe_aux_outardes, 
    {
        prc_biome_recharge_pointe_aux_outardes(output_path = "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/processed", 
            input_files = list(tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_biodiversity_2021, 
                tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_biodiversity_2022, 
                tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_biodiversity_2023, 
                tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_logbook_2021, 
                tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_logbook_2022, 
                tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_logbook_2023, 
                tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_pointe_aux_outardes_logbook_2024))
        c("workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/processed/biome_recharge_pointe-aux-outardes_logbooks.csv", 
        "workspace/data/harvested/biome_recharge_pointe-aux-outardes-1.0.0/processed/biome_recharge_pointe-aux-outardes_biodiversity.csv"
        )
    }, format = "file")),
    list(list(tar_target(tg_23daffc4_dd6a_441b_8897_19aaa8972abf_sainte_flavie_logbook_2024, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "sainte-flavie/logbook/sf_logbook_2024.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_sainte-flavie-1.0.0/raw/sf_logbook_2024.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_sainte-flavie-1.0.0/raw/sf_logbook_2024.csv"
    }, format = "file")), tar_target(tg_23daffc4_dd6a_441b_8897_19aaa8972abf_processing_biome_recharge_sainte_flavie, 
    {
        prc_biome_recharge_sainte_flavie(output_path = "workspace/data/harvested/biome_recharge_sainte-flavie-1.0.0/processed", 
            input_files = list(tg_23daffc4_dd6a_441b_8897_19aaa8972abf_sainte_flavie_logbook_2024))
        "workspace/data/harvested/biome_recharge_sainte-flavie-1.0.0/processed/biome_recharge_sainte-flavie_logbooks.csv"
    }, format = "file")),
    list(list(tar_target(tg_bae62dca_7abd_4c98_939e_5d2882d21329_sainte_luce_logbook_2024, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "sainte-luce/logbook/sl_logbook_2024.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/biome_recharge_sainte-luce-1.0.0/raw/sl_logbook_2024.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/biome_recharge_sainte-luce-1.0.0/raw/sl_logbook_2024.csv"
    }, format = "file")), tar_target(tg_bae62dca_7abd_4c98_939e_5d2882d21329_processing_biome_recharge_sainte_luce, 
    {
        prc_biome_recharge_sainte_luce(output_path = "workspace/data/harvested/biome_recharge_sainte-luce-1.0.0/processed", 
            input_files = list(tg_bae62dca_7abd_4c98_939e_5d2882d21329_sainte_luce_logbook_2024))
        "workspace/data/harvested/biome_recharge_sainte-luce-1.0.0/processed/biome_recharge_sainte-luce_logbooks.csv"
    }, format = "file")),
    list(tarchetypes::tar_download(tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Metadata_on_Study_Sites___Maritimes, 
    url = "https://cabin-rcba.ec.gc.ca/Cabin/opendata/cabin_study_data_mda01_1987-present.csv", 
    path = "workspace/data/harvested/cabin_aquatic_biomonitoring-1.0.0/raw/cabin_study_data_maritimes.csv"), 
    tarchetypes::tar_download(tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Habitat_Data___Maritimes, 
        url = "https://cabin-rcba.ec.gc.ca/Cabin/opendata/cabin_habitat_data_mda01_1987-present.csv", 
        path = "workspace/data/harvested/cabin_aquatic_biomonitoring-1.0.0/raw/cabin_habitat_data_maritimes.csv"), 
    tarchetypes::tar_download(tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Benthic_Macroinvertebrate_Data___Maritimes, 
        url = "https://cabin-rcba.ec.gc.ca/Cabin/opendata/cabin_benthic_data_mda01_1987-present.csv", 
        path = "workspace/data/harvested/cabin_aquatic_biomonitoring-1.0.0/raw/cabin_benthic_data_maritimes.csv"), 
    tarchetypes::tar_download(tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Metadata_on_Study_Sites___St_Lawrence, 
        url = "https://cabin-rcba.ec.gc.ca/Cabin/opendata/cabin_study_data_mda02_1987-present.csv", 
        path = "workspace/data/harvested/cabin_aquatic_biomonitoring-1.0.0/raw/cabin_study_data_st_lawrence.csv"), 
    tarchetypes::tar_download(tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Habitat_Data___St_Lawrence, 
        url = "https://cabin-rcba.ec.gc.ca/Cabin/opendata/cabin_habitat_data_mda02_1987-present.csv", 
        path = "workspace/data/harvested/cabin_aquatic_biomonitoring-1.0.0/raw/cabin_habitat_data_st_lawrence.csv"), 
    tarchetypes::tar_download(tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Benthic_Macroinvertebrate_Data___St_Lawrence, 
        url = "https://cabin-rcba.ec.gc.ca/Cabin/opendata/cabin_benthic_data_mda02_1987-present.csv", 
        path = "workspace/data/harvested/cabin_aquatic_biomonitoring-1.0.0/raw/cabin_benthic_data_st_lawrence.csv"), 
    tar_target(tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_process_cabin_aquatic_biomonitoring, 
        {
            prc_cabin_aquatic_biomonitoring(output_path = "workspace/data/harvested/cabin_aquatic_biomonitoring-1.0.0/processed", 
                input_files = list(tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Metadata_on_Study_Sites___Maritimes, 
                  tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Habitat_Data___Maritimes, 
                  tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Benthic_Macroinvertebrate_Data___Maritimes, 
                  tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Metadata_on_Study_Sites___St_Lawrence, 
                  tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Habitat_Data___St_Lawrence, 
                  tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_Benthic_Macroinvertebrate_Data___St_Lawrence))
            c("workspace/data/harvested/cabin_aquatic_biomonitoring-1.0.0/processed/cabin_study_data.csv", 
            "workspace/data/harvested/cabin_aquatic_biomonitoring-1.0.0/processed/cabin_habitat_data.csv", 
            "workspace/data/harvested/cabin_aquatic_biomonitoring-1.0.0/processed/cabin_benthic_data.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_Event_Data, 
    url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_e234a1a5-e21e-4c09-bc77-d92d72796ae7/kelp_event-data_2018-2019.csv", 
    path = "workspace/data/harvested/inventaire_batture_alouettes-1.0.0/raw/kelp_event-data_2018-2019.csv"), 
    tarchetypes::tar_download(tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_Occurrence_Data, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_e234a1a5-e21e-4c09-bc77-d92d72796ae7/kelp_occurrence-data_2018-2019.csv", 
        path = "workspace/data/harvested/inventaire_batture_alouettes-1.0.0/raw/kelp_occurrence-data_2018-2019.csv"), 
    tar_target(tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_process_inventaire_batture_alouettes, 
        {
            prc_inventaire_batture_alouettes(output_path = "workspace/data/harvested/inventaire_batture_alouettes-1.0.0/processed", 
                input_files = list(tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_Event_Data, 
                  tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_Occurrence_Data))
            c("workspace/data/harvested/inventaire_batture_alouettes-1.0.0/processed/kelp_events.csv", 
            "workspace/data/harvested/inventaire_batture_alouettes-1.0.0/processed/kelp_occurrences.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Evenements_echantillonnage, 
    url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_4bb77d86-b94e-4f61-b91b-fdcfd6ecbaed/macroalgae-macroinvertebrates_event-data_2019.csv", 
    path = "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/raw/macroalgae-macroinvertebrates_event-data_2019.csv"), 
    tarchetypes::tar_download(tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Occurrences_macroinvertebres, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_4bb77d86-b94e-4f61-b91b-fdcfd6ecbaed/macroalgae-macroinvertebrates_occurrence-data_2019.csv", 
        path = "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/raw/macroalgae-macroinvertebrates_occurrence-data_2019.csv"), 
    tarchetypes::tar_download(tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Mesures_abiotiques, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_4bb77d86-b94e-4f61-b91b-fdcfd6ecbaed/macroalgae-macroinvertebrates_abiotic-measurement_2019.csv", 
        path = "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/raw/macroalgae-macroinvertebrates_abiotic-measurement_2019.csv"), 
    tar_target(tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_process_inventaire_macroalgues_macroinvertebres, 
        {
            prc_inventaire_macroalgues_macroinvertebres(output_path = "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/processed", 
                input_files = list(tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Evenements_echantillonnage, 
                  tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Occurrences_macroinvertebres, 
                  tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_Mesures_abiotiques))
            c("workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/processed/events.csv", 
            "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/processed/occurrences.csv", 
            "workspace/data/harvested/inventaire_macroalgues_macroinvertebres-1.0.0/processed/abiotic.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Evenements_echantillonnage, 
    url = "https://catalogue.ogsl.ca/data/cegep-sherbrooke/ca-cioos_b943abc0-09be-43c6-a003-efa665a6c8a9/DwC_cegepSher_pointe-john_event_2021.csv", 
    path = "workspace/data/harvested/inventaire_pointe_john-1.0.0/raw/events_pointe_john.csv"), 
    tarchetypes::tar_download(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Mesures_physico_chimiques, 
        url = "https://catalogue.ogsl.ca/data/cegep-sherbrooke/ca-cioos_b943abc0-09be-43c6-a003-efa665a6c8a9/DwC_cegepSher_pointe-john_event-emof_2021.csv", 
        path = "workspace/data/harvested/inventaire_pointe_john-1.0.0/raw/physico_chem_pointe_john.csv"), 
    tarchetypes::tar_download(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Observations_taxons, 
        url = "https://catalogue.ogsl.ca/data/cegep-sherbrooke/ca-cioos_b943abc0-09be-43c6-a003-efa665a6c8a9/DwC_cegepSher_pointe-john_occurrence_2021.csv", 
        path = "workspace/data/harvested/inventaire_pointe_john-1.0.0/raw/occurrences_pointe_john.csv"), 
    tarchetypes::tar_download(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Recouvrement_especes, 
        url = "https://catalogue.ogsl.ca/data/cegep-sherbrooke/ca-cioos_b943abc0-09be-43c6-a003-efa665a6c8a9/DwC_cegepSher_pointe-john_occurrence-emof_2021.csv", 
        path = "workspace/data/harvested/inventaire_pointe_john-1.0.0/raw/species_recovery_pointe_john.csv"), 
    tar_target(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_processing_inventaire_pointe_john, 
        {
            prc_inventaire_pointe_john(output_path = "workspace/data/harvested/inventaire_pointe_john-1.0.0/processed", 
                input_files = list(tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Evenements_echantillonnage, 
                  tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Mesures_physico_chimiques, 
                  tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Observations_taxons, 
                  tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_Recouvrement_especes))
            c("workspace/data/harvested/inventaire_pointe_john-1.0.0/processed/events_pointe_john.csv", 
            "workspace/data/harvested/inventaire_pointe_john-1.0.0/processed/occurrences_pointe_john.csv", 
            "workspace/data/harvested/inventaire_pointe_john-1.0.0/processed/physico_chem_pointe_john.csv", 
            "workspace/data/harvested/inventaire_pointe_john-1.0.0/processed/species_recovery_pointe_john.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Evenements_echantillonnage, 
    url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_0756dd24-4bf4-47ab-a325-c83f9ed763da/DL_CPD_PPO_EVENT_Fr_20230830.csv", 
    path = "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/raw/evenements_cpd.csv"), 
    tarchetypes::tar_download(tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Occurrences, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_0756dd24-4bf4-47ab-a325-c83f9ed763da/DL_CPD_PPO_OCCURENCE_Fr_20230830.csv", 
        path = "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/raw/occurrences_cpd.csv"), 
    tarchetypes::tar_download(tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Dictionnaire_des_donnees, 
        url = "https://catalogue.ogsl.ca/data/dfo-mpo/ca-cioos_0756dd24-4bf4-47ab-a325-c83f9ed763da/DataDictionary_DictionnaireDonnees_MP_AR20230824.csv", 
        path = "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/raw/dictionnaire_donnees.csv"), 
    tar_target(tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_process_invertebres_vegetation_saint_laurent, 
        {
            prc_invertebres_vegetation_saint_laurent(output_path = "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/processed", 
                input_files = list(tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Evenements_echantillonnage, 
                  tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Occurrences, 
                  tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_Dictionnaire_des_donnees))
            c("workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/processed/evenements_cpd.csv", 
            "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/processed/occurrences_cpd.csv", 
            "workspace/data/harvested/invertebres_vegetation_saint_laurent-1.0.0/processed/dictionnaire_donnees.csv"
            )
        }, format = "file")),
    list(list(tar_target(tg_e246927f_d1b7_4450_8f91_a6e9b91c0c64_Cartographie_Ecosystèmes_Qc_Maritime_2021, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "resilience_cotiere/CartographieEcosystemes_QcMaritime_2021.gdb.zip", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/resilience_cotiere-1.0.0/raw/CartographieEcosystemes_QcMaritime_2021.gdb.zip", 
            overwrite = TRUE)
        "workspace/data/harvested/resilience_cotiere-1.0.0/raw/CartographieEcosystemes_QcMaritime_2021.gdb.zip"
    }, format = "file")), list(tar_target(tg_e246927f_d1b7_4450_8f91_a6e9b91c0c64_Côtes_Qc_Maritime_2022, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "resilience_cotiere/Cotes_QcMaritime_2022_03_03.gdb.zip", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/resilience_cotiere-1.0.0/raw/Cotes_QcMaritime_2022_03_03.gdb.zip", 
            overwrite = TRUE)
        "workspace/data/harvested/resilience_cotiere-1.0.0/raw/Cotes_QcMaritime_2022_03_03.gdb.zip"
    }, format = "file")), tar_target(tg_e246927f_d1b7_4450_8f91_a6e9b91c0c64_processing_resilience_cotiere, 
    {
        prc_resilience_cotiere(output_path = "workspace/data/harvested/resilience_cotiere-1.0.0/processed", 
            input_files = list(tg_e246927f_d1b7_4450_8f91_a6e9b91c0c64_Cartographie_Ecosystèmes_Qc_Maritime_2021, 
                tg_e246927f_d1b7_4450_8f91_a6e9b91c0c64_Côtes_Qc_Maritime_2022))
        c("workspace/data/harvested/resilience_cotiere-1.0.0/processed/resilience_cotiere_ecosystemes.gpkg", 
        "workspace/data/harvested/resilience_cotiere-1.0.0/processed/resilience_cotiere_ecosystemes_simple.gpkg", 
        "workspace/data/harvested/resilience_cotiere-1.0.0/processed/resilience_cotiere_cotes.gpkg"
        )
    }, format = "file")),
    list(list(tar_target(tg_860d96c4_efd7_4d76_a6d7_207c0b927815_intertidal, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "yanick_gendreau/yanick_intertidal_data_abundance.csv", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/yanick_gendreau-1.0.0/raw/yanick_intertidal_data_abundance.csv", 
            overwrite = TRUE)
        "workspace/data/harvested/yanick_gendreau-1.0.0/raw/yanick_intertidal_data_abundance.csv"
    }, format = "file")), list(tar_target(tg_860d96c4_efd7_4d76_a6d7_207c0b927815_intertidal_subtidal, 
    {
        googleCloudStorageR::gcs_auth("workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        Sys.setenv(GCS_AUTH_FILE = "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json")
        googleCloudStorageR::gcs_get_object(object_name = "yanick_gendreau/Liste_Sp_CindyGrant.txt", 
            bucket = "biome-resilience-cotiere", saveToDisk = "workspace/data/harvested/yanick_gendreau-1.0.0/raw/Liste_Sp_CindyGrant.txt", 
            overwrite = TRUE)
        "workspace/data/harvested/yanick_gendreau-1.0.0/raw/Liste_Sp_CindyGrant.txt"
    }, format = "file")), tar_target(tg_860d96c4_efd7_4d76_a6d7_207c0b927815_processing_yanick_gendreau, 
    {
        prc_yanick_gendreau(output_path = "workspace/data/harvested/yanick_gendreau-1.0.0/processed", 
            input_files = list(tg_860d96c4_efd7_4d76_a6d7_207c0b927815_intertidal, 
                tg_860d96c4_efd7_4d76_a6d7_207c0b927815_intertidal_subtidal))
        c("workspace/data/harvested/yanick_gendreau-1.0.0/processed/yanick_gendreau_intertidal.csv", 
        "workspace/data/harvested/yanick_gendreau-1.0.0/processed/yanick_gendreau_intertidal_subtidal.csv"
        )
    }, format = "file")),
    list(tarchetypes::tar_download(tg_66ac503f_ead2_46a4_afc9_e658e459efef_Donnees_echantillonnage, 
    url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_f10f496a-acf4-4274-9c7b-7a005bcf54ed/DwC_zip_rne_marais_bmv_2019-2021.zip", 
    path = "workspace/data/harvested/zip_inventaire_marais_baie_mille_vaches-1.0.0/raw/DwC_marais_bmv_2019-2021.zip"), 
    tarchetypes::tar_download(tg_66ac503f_ead2_46a4_afc9_e658e459efef_Rapport_de_caracterisation, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_f10f496a-acf4-4274-9c7b-7a005bcf54ed/ziprne_portrait_ecogeomorphologique.pdf", 
        path = "workspace/data/harvested/zip_inventaire_marais_baie_mille_vaches-1.0.0/raw/portrait_ecogeomorphologique.pdf"), 
    tarchetypes::tar_download(tg_66ac503f_ead2_46a4_afc9_e658e459efef_Rapport_hydrogeomorphologique_et_sedimentologique, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_f10f496a-acf4-4274-9c7b-7a005bcf54ed/ziprne_caracterisation_hydrogeomorph_sedimentolo_plage_pointe_a_boisvert.pdf", 
        path = "workspace/data/harvested/zip_inventaire_marais_baie_mille_vaches-1.0.0/raw/hydrogeomorph_sedimentologie_pointe_a_boisvert.pdf"), 
    tar_target(tg_66ac503f_ead2_46a4_afc9_e658e459efef_process_zip_inventaire_marais_baie_mille_vaches, 
        {
            prc_zip_inventaire_marais_baie_mille_vaches(output_path = "workspace/data/harvested/zip_inventaire_marais_baie_mille_vaches-1.0.0/processed", 
                input_files = list(tg_66ac503f_ead2_46a4_afc9_e658e459efef_Donnees_echantillonnage))
            c("workspace/data/harvested/zip_inventaire_marais_baie_mille_vaches-1.0.0/processed/marais_bmv_events.csv", 
            "workspace/data/harvested/zip_inventaire_marais_baie_mille_vaches-1.0.0/processed/marais_bmv_occurrences.csv", 
            "workspace/data/harvested/zip_inventaire_marais_baie_mille_vaches-1.0.0/processed/marais_bmv_abiotic.csv", 
            "workspace/data/harvested/zip_inventaire_marais_baie_mille_vaches-1.0.0/processed/marais_bmv_abundance.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_Rapport_de_caracterisation, 
    url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_a5125bd3-60e3-4c89-89b6-2d3a8728d10f/Portrait_ZIPRNE_bergeronnes_2022.pdf", 
    path = "workspace/data/harvested/zip_inventaire_marais_bergeronnes-1.0.0/raw/portrait_bergeronnes_2022.pdf"), 
    tarchetypes::tar_download(tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_Evenements_echantillonnage, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_a5125bd3-60e3-4c89-89b6-2d3a8728d10f/zip-rne_marais-bergeronnes_event_2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_bergeronnes-1.0.0/raw/marais_bergeronnes_events.csv"), 
    tarchetypes::tar_download(tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_Mesures_abiotiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_a5125bd3-60e3-4c89-89b6-2d3a8728d10f/zip-rne_marais-bergeronnes_event-emof_2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_bergeronnes-1.0.0/raw/marais_bergeronnes_abiotic.csv"), 
    tarchetypes::tar_download(tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_Occurrences_biologiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_a5125bd3-60e3-4c89-89b6-2d3a8728d10f/zip-rne_marais-bergeronnes_occurrence_2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_bergeronnes-1.0.0/raw/marais_bergeronnes_occurrences.csv"), 
    tarchetypes::tar_download(tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_Donnees_abondance, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_a5125bd3-60e3-4c89-89b6-2d3a8728d10f/zip-rne_marais-bergeronnes_occurrence-emof_2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_bergeronnes-1.0.0/raw/marais_bergeronnes_abundance.csv"), 
    tar_target(tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_process_zip_inventaire_marais_bergeronnes, 
        {
            prc_zip_inventaire_marais_bergeronnes(output_path = "workspace/data/harvested/zip_inventaire_marais_bergeronnes-1.0.0/processed", 
                input_files = list(tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_Evenements_echantillonnage, 
                  tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_Mesures_abiotiques, 
                  tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_Occurrences_biologiques, 
                  tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_Donnees_abondance))
            c("workspace/data/harvested/zip_inventaire_marais_bergeronnes-1.0.0/processed/marais_bergeronnes_events.csv", 
            "workspace/data/harvested/zip_inventaire_marais_bergeronnes-1.0.0/processed/marais_bergeronnes_abiotic.csv", 
            "workspace/data/harvested/zip_inventaire_marais_bergeronnes-1.0.0/processed/marais_bergeronnes_occurrences.csv", 
            "workspace/data/harvested/zip_inventaire_marais_bergeronnes-1.0.0/processed/marais_bergeronnes_abundance.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_645bee2a_0a34_460a_9062_cb276213ce96_Evenements_echantillonnage, 
    url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_0925e105-860e-4fe7-83ac-afc5e4c2699e/zip-rne_marais-hick_event.csv", 
    path = "workspace/data/harvested/zip_inventaire_marais_hickey-1.0.0/raw/marais_hick_events.csv"), 
    tarchetypes::tar_download(tg_645bee2a_0a34_460a_9062_cb276213ce96_Mesures_abiotiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_0925e105-860e-4fe7-83ac-afc5e4c2699e/zip-rne_marais-hick_event_emof_2022.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_hickey-1.0.0/raw/marais_hick_abiotic.csv"), 
    tarchetypes::tar_download(tg_645bee2a_0a34_460a_9062_cb276213ce96_Occurrences_biologiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_0925e105-860e-4fe7-83ac-afc5e4c2699e/zip-rne_marais-hick_occurrence_2022.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_hickey-1.0.0/raw/marais_hick_occurrences.csv"), 
    tarchetypes::tar_download(tg_645bee2a_0a34_460a_9062_cb276213ce96_Donnees_abondance, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_0925e105-860e-4fe7-83ac-afc5e4c2699e/zip-rne_marais-hick_occurrence_emof_2022.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_hickey-1.0.0/raw/marais_hick_abundance.csv"), 
    tar_target(tg_645bee2a_0a34_460a_9062_cb276213ce96_process_zip_inventaire_marais_hickey, 
        {
            prc_zip_inventaire_marais_hickey(output_path = "workspace/data/harvested/zip_inventaire_marais_hickey-1.0.0/processed", 
                input_files = list(tg_645bee2a_0a34_460a_9062_cb276213ce96_Evenements_echantillonnage, 
                  tg_645bee2a_0a34_460a_9062_cb276213ce96_Mesures_abiotiques, 
                  tg_645bee2a_0a34_460a_9062_cb276213ce96_Occurrences_biologiques, 
                  tg_645bee2a_0a34_460a_9062_cb276213ce96_Donnees_abondance))
            c("workspace/data/harvested/zip_inventaire_marais_hickey-1.0.0/processed/marais_hick_events.csv", 
            "workspace/data/harvested/zip_inventaire_marais_hickey-1.0.0/processed/marais_hick_occurrences.csv", 
            "workspace/data/harvested/zip_inventaire_marais_hickey-1.0.0/processed/marais_hick_abiotic.csv", 
            "workspace/data/harvested/zip_inventaire_marais_hickey-1.0.0/processed/marais_hick_abundance.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_1a7d4967_4a9d_446c_a080_c93755a24be9_Rapport_de_caracterisation, 
    url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_46d3ba2e-2fd3-4aad-a51a-f8343fbe6a73/Portrait_PAO_2022_ZIPRNE.pdf", 
    path = "workspace/data/harvested/zip_inventaire_marais_pointe_aux_outardes-1.0.0/raw/portrait_pao_2022.pdf"), 
    tarchetypes::tar_download(tg_1a7d4967_4a9d_446c_a080_c93755a24be9_Evenements_echantillonnage, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_46d3ba2e-2fd3-4aad-a51a-f8343fbe6a73/zip-rne_marais-pao_event_2020-2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_pointe_aux_outardes-1.0.0/raw/marais_pao_events.csv"), 
    tarchetypes::tar_download(tg_1a7d4967_4a9d_446c_a080_c93755a24be9_Mesures_abiotiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_46d3ba2e-2fd3-4aad-a51a-f8343fbe6a73/zip-rne_marais-pao_event_emof_2020-2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_pointe_aux_outardes-1.0.0/raw/marais_pao_abiotic.csv"), 
    tarchetypes::tar_download(tg_1a7d4967_4a9d_446c_a080_c93755a24be9_Occurrences_biologiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_46d3ba2e-2fd3-4aad-a51a-f8343fbe6a73/zip-rne_marais-pao_occurrence_2020-2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_pointe_aux_outardes-1.0.0/raw/marais_pao_occurrences.csv"), 
    tarchetypes::tar_download(tg_1a7d4967_4a9d_446c_a080_c93755a24be9_Donnees_abondance, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_46d3ba2e-2fd3-4aad-a51a-f8343fbe6a73/zip-rne_marais-pao_occurrence_emof_2020-2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_pointe_aux_outardes-1.0.0/raw/marais_pao_abundance.csv"), 
    tar_target(tg_1a7d4967_4a9d_446c_a080_c93755a24be9_process_zip_inventaire_marais_pointe_aux_outardes, 
        {
            prc_zip_inventaire_marais_pointe_aux_outardes(output_path = "workspace/data/harvested/zip_inventaire_marais_pointe_aux_outardes-1.0.0/processed", 
                input_files = list(tg_1a7d4967_4a9d_446c_a080_c93755a24be9_Evenements_echantillonnage, 
                  tg_1a7d4967_4a9d_446c_a080_c93755a24be9_Mesures_abiotiques, 
                  tg_1a7d4967_4a9d_446c_a080_c93755a24be9_Occurrences_biologiques, 
                  tg_1a7d4967_4a9d_446c_a080_c93755a24be9_Donnees_abondance))
            c("workspace/data/harvested/zip_inventaire_marais_pointe_aux_outardes-1.0.0/processed/marais_pao_events.csv", 
            "workspace/data/harvested/zip_inventaire_marais_pointe_aux_outardes-1.0.0/processed/marais_pao_abiotic.csv", 
            "workspace/data/harvested/zip_inventaire_marais_pointe_aux_outardes-1.0.0/processed/marais_pao_occurrences.csv", 
            "workspace/data/harvested/zip_inventaire_marais_pointe_aux_outardes-1.0.0/processed/marais_pao_abundance.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Evenements_echantillonnage, 
    url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_event_2019-2021.csv", 
    path = "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/raw/marais_pointe_fortin_events.csv"), 
    tarchetypes::tar_download(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Mesures_abiotiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_event_emof_2019-2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/raw/marais_pointe_fortin_abiotic.csv"), 
    tarchetypes::tar_download(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Occurrences_biologiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_occurrence_2019-2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/raw/marais_pointe_fortin_occurrences.csv"), 
    tarchetypes::tar_download(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Donnees_abondance, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_occurrence_emof_2019-2021.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/raw/marais_pointe_fortin_abundance.csv"), 
    tar_target(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_process_zip_inventaire_marais_pointe_fortin, 
        {
            prc_zip_inventaire_marais_pointe_fortin(output_path = "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/processed", 
                input_files = list(tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Evenements_echantillonnage, 
                  tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Mesures_abiotiques, 
                  tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Occurrences_biologiques, 
                  tg_01fab37f_efbc_433d_8a08_d717200c0ff7_Donnees_abondance))
            c("workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/processed/marais_pointe_fortin_events.csv", 
            "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/processed/marais_pointe_fortin_abiotic.csv", 
            "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/processed/marais_pointe_fortin_occurrences.csv", 
            "workspace/data/harvested/zip_inventaire_marais_pointe_fortin-1.0.0/processed/marais_pointe_fortin_abundance.csv"
            )
        }, format = "file")),
    list(tarchetypes::tar_download(tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_Rapport_de_caracterisation, 
    url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_5374b582-43aa-4ffa-8361-4a0d9f1f6b8e/caract_portneuf-sur-mer_comiteziprne.pdf", 
    path = "workspace/data/harvested/zip_inventaire_marais_portneuf_sur_mer-1.0.0/raw/caract_portneuf-sur-mer.pdf"), 
    tarchetypes::tar_download(tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_Evenements_echantillonnage, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_5374b582-43aa-4ffa-8361-4a0d9f1f6b8e/zip-rne_marais-psm_event_2018.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_portneuf_sur_mer-1.0.0/raw/marais_portneuf_sur_mer_events.csv"), 
    tarchetypes::tar_download(tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_Mesures_abiotiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_5374b582-43aa-4ffa-8361-4a0d9f1f6b8e/zip-rne_marais-psm_event_emof_2018.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_portneuf_sur_mer-1.0.0/raw/marais_portneuf_sur_mer_abiotic.csv"), 
    tarchetypes::tar_download(tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_Occurrences_biologiques, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_5374b582-43aa-4ffa-8361-4a0d9f1f6b8e/zip-rne_marais-psm_occurrence_2018.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_portneuf_sur_mer-1.0.0/raw/marais_portneuf_sur_mer_occurrences.csv"), 
    tarchetypes::tar_download(tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_Donnees_abondance, 
        url = "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_5374b582-43aa-4ffa-8361-4a0d9f1f6b8e/zip-rne_marais-psm_occurrence_emof_2018.csv", 
        path = "workspace/data/harvested/zip_inventaire_marais_portneuf_sur_mer-1.0.0/raw/marais_portneuf_sur_mer_abundance.csv"), 
    tar_target(tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_process_zip_inventaire_marais_portneuf_sur_mer, 
        {
            prc_zip_inventaire_marais_portneuf_sur_mer(output_path = "workspace/data/harvested/zip_inventaire_marais_portneuf_sur_mer-1.0.0/processed", 
                input_files = list(tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_Evenements_echantillonnage, 
                  tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_Mesures_abiotiques, 
                  tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_Occurrences_biologiques, 
                  tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_Donnees_abondance))
            c("workspace/data/harvested/zip_inventaire_marais_portneuf_sur_mer-1.0.0/processed/marais_portneuf_sur_mer_events.csv", 
            "workspace/data/harvested/zip_inventaire_marais_portneuf_sur_mer-1.0.0/processed/marais_portneuf_sur_mer_abiotic.csv", 
            "workspace/data/harvested/zip_inventaire_marais_portneuf_sur_mer-1.0.0/processed/marais_portneuf_sur_mer_occurrences.csv", 
            "workspace/data/harvested/zip_inventaire_marais_portneuf_sur_mer-1.0.0/processed/marais_portneuf_sur_mer_abundance.csv"
            )
        }, format = "file")),
    list(tar_target(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data, 
    {
        int_biodiversity_data(output_path = "workspace/data/analyzed/biodiversity_data-1.0.0", 
            input_files = list(tg_2b9ea288_e863_4cf3_9196_2dc19a5f5def_process_biodiversite_piei, 
                tg_db49664a_0e7d_47e8_a3a1_63bc29881c61_processing_biome_io_herbier_benthos, 
                tg_39dc578d_4b4d_465f_819f_4aac5b86ee7d_processing_biome_recharge_lagrave, 
                tg_c6b58e09_2b7e_4f24_a1d1_3826acbf5840_processing_biome_recharge_maria, 
                tg_e7c1ea73_41f3_4bf0_a5f0_16ad97416965_processing_biome_recharge_pointe_aux_loups, 
                tg_0eeaf1d9_5b3f_4c57_82db_0d8e6036619e_processing_biome_recharge_pointe_aux_outardes, 
                tg_23daffc4_dd6a_441b_8897_19aaa8972abf_processing_biome_recharge_sainte_flavie, 
                tg_bae62dca_7abd_4c98_939e_5d2882d21329_processing_biome_recharge_sainte_luce, 
                tg_1cac3c56_ed56_49f5_897c_1b7cf40605c5_process_cabin_aquatic_biomonitoring, 
                tg_dfbfc2d7_697f_4801_b859_91bf4c1575df_process_inventaire_batture_alouettes, 
                tg_71e5ee2d_2433_455d_8434_9a9fa26afde6_process_inventaire_macroalgues_macroinvertebres, 
                tg_0a5569d7_5b9c_44df_9fba_1cc19c95f2ab_processing_inventaire_pointe_john, 
                tg_d66fe58a_b279_4e2c_8a81_71ab068f2a04_process_invertebres_vegetation_saint_laurent, 
                tg_860d96c4_efd7_4d76_a6d7_207c0b927815_processing_yanick_gendreau, 
                tg_66ac503f_ead2_46a4_afc9_e658e459efef_process_zip_inventaire_marais_baie_mille_vaches, 
                tg_e0f4140b_48b8_47d4_8006_af63af48a1c2_process_zip_inventaire_marais_bergeronnes, 
                tg_645bee2a_0a34_460a_9062_cb276213ce96_process_zip_inventaire_marais_hickey, 
                tg_1a7d4967_4a9d_446c_a080_c93755a24be9_process_zip_inventaire_marais_pointe_aux_outardes, 
                tg_01fab37f_efbc_433d_8a08_d717200c0ff7_process_zip_inventaire_marais_pointe_fortin, 
                tg_36f7af6b_8d9c_439f_a838_a25a9c08efe3_process_zip_inventaire_marais_portneuf_sur_mer, 
                tg_e246927f_d1b7_4450_8f91_a6e9b91c0c64_processing_resilience_cotiere))
        c("workspace/data/analyzed/biodiversity_data-1.0.0/biodiversity_data.sqlite", 
        "workspace/data/analyzed/biodiversity_data-1.0.0/biodiversity_data.svg"
        )
    }, format = "file")),
    list(tar_target(tg_ecb45967_f0b1_4f8d_901b_2119dc43be04_figures_events_ecosystems, 
    {
        fig_events_ecosystems(output_path = "workspace/data/analyzed/figures_events_ecosystems-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data, 
                tg_e246927f_d1b7_4450_8f91_a6e9b91c0c64_processing_resilience_cotiere, 
                tg_d1d4149b_ba3c_40ac_890d_b73c2b619423_indicateurs_et_ecosystemes))
        "workspace/data/analyzed/figures_events_ecosystems-1.0.0/projet_indicateurs.zip"
    }, format = "file")),
    list(tar_target(tg_d1d4149b_ba3c_40ac_890d_b73c2b619423_indicateurs_et_ecosystemes, 
    {
        ana_indicateurs_ecosystemes(output_path = "workspace/data/analyzed/indicateurs_ecosystemes-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_abondance, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_biomasse, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_dominance, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_richesse_specifique, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_diversite_shannon, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_equitabilite_pielou, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_diversite_simpson, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_indices_hill, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_rarefaction_hurlbert, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_diversite_taxonomique, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_bbi, 
                tg_ff15a782_7ee4_4327_a72c_a23d640d219b_bo2a_bopa))
        "workspace/data/analyzed/indicateurs_ecosystemes-1.0.0/indicateurs_ecosystemes.csv"
    }, format = "file")),
    list(tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_abondance, 
    {
        ana_abondance(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/abondance.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_biomasse, 
    {
        ana_biomasse(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/biomasse.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_dominance, 
    {
        ana_dominance(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/dominance.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_richesse_specifique, 
    {
        ana_richesse_specifique(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/richesse_specifique.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_diversite_shannon, 
    {
        ana_diversite_shannon(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/diversite_shannon.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_equitabilite_pielou, 
    {
        ana_equitabilite_pielou(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/equitabilite_pielou.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_diversite_simpson, 
    {
        ana_diversite_simpson(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/diversite_simpson.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_indices_hill, 
    {
        ana_indices_hill(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/indices_hill.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_rarefaction_hurlbert, 
    {
        ana_rarefaction_hurlbert(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/rarefaction_hurlbert.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_dissimilarite_bray_curtis, 
    {
        ana_dissimilarite_bray_curtis(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/dissimilarite_bray_curtis.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_diversite_taxonomique, 
    {
        ana_diversite_taxonomique(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/diversite_taxonomique.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_bbi, 
    {
        ana_bbi(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/bbi.csv"
    }, format = "file"), tar_target(tg_ff15a782_7ee4_4327_a72c_a23d640d219b_bo2a_bopa, 
    {
        ana_bo2a_bopa(output_path = "workspace/data/analyzed/indicateurs-1.0.0", 
            input_files = list(tg_93c9fa26_0a59_4d41_b037_2bad00e2b97c_integrate_biodiversity_data))
        "workspace/data/analyzed/indicateurs-1.0.0/bo2a_bopa.csv"
    }, format = "file"))
)
