pipeline:
  id: 39dc578d-4b4d-465f-819f-4aac5b86ee7d
  name: biome_recharge_lagrave
  version: 1.0.0
  package_version: 0.0.0.9001
  created_at: 2025-01-30 16:23:39
  last_modified: 2025-01-30 16:23:39
  description: >
    Ce pipeline collecte des données de biodiversité et de suivi logistique du site de recharge de La Grave.

  metadata:
    source_name: "BIOME - Recharge La Grave"
    data_type: "CSV"
    file_size: "Inconnu"
    license: "Données en accès restreint"
    last_updated: "2024"
    geographic_coverage:
      region: "Site de recharge La Grave"
      bounding_box:
        - null
        - null
        - null
        - null
    temporal_coverage:
      start_date: "2021-01-01"
      end_date: "2024-12-31"
    variables:
      - biodiversité
      - logbook
    data_quality: 
      - "Données validées par le laboratoire BIOME"

  bibliography:
    - "@TechReport{biome_lagrave_2024,
        title = {Suivi de la recharge de plage à La Grave},
        author = {{BIOME}},
        year = {2024},
        institution = {{Université Laval}},
      }"

  download:
    sources:
      - name: lagrave_biodiversity 2021
        description: Données de biodiversité de La Grave
        source_type: "gcs"
        urls: "biome-resilience-cotiere"
        asset: "lagrave/biodiversity/lg_biodiversity_2021.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: lagrave_biodiversity 2022
        description: Données de biodiversité de La Grave
        source_type: "gcs"
        urls: "biome-resilience-cotiere"
        asset: "lagrave/biodiversity/lg_biodiversity_2022.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: lagrave_biodiversity 2023
        description: Données de biodiversité de La Grave
        source_type: "gcs"
        urls: "biome-resilience-cotiere"
        asset: "lagrave/biodiversity/lg_biodiversity_2023.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: lagrave_logbook 2021
        description: Données logistiques du site de La Grave
        source_type: "gcs"
        urls: "biome-resilience-cotiere"
        asset: "lagrave/logbook/lg_logbook_2021.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: lagrave_logbook 2022
        description: Données logistiques du site de La Grave
        source_type: "gcs"
        urls: "biome-resilience-cotiere"
        asset: "lagrave/logbook/lg_logbook_2022.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: lagrave_logbook 2023
        description: Données logistiques du site de La Grave
        source_type: "gcs"
        urls: "biome-resilience-cotiere"
        asset: "lagrave/logbook/lg_logbook_2023.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

      - name: lagrave_logbook 2024
        description: Données logistiques du site de La Grave
        source_type: "gcs"
        urls: "biome-resilience-cotiere"
        asset: "lagrave/logbook/lg_logbook_2024.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

  processing:
    sources:
      - name: processing biome_recharge_lagrave
        script: prc_biome_recharge_lagrave
        input_files:
          - lagrave_biodiversity 2021
          - lagrave_biodiversity 2022
          - lagrave_biodiversity 2023
          - lagrave_logbook 2021
          - lagrave_logbook 2022
          - lagrave_logbook 2023
          - lagrave_logbook 2024
        output_files: 
          - biome_recharge_lagrave_logbooks.csv
          - biome_recharge_lagrave_biodiversity.csv

  output:
    output_dir: "workspace/data/harvested/recharge_lagrave/"
    log_dir: "workspace/logs/"
    archive_raw: true
