pipeline:
  id: db49664a-0e7d-47e8-a3a1-63bc29881c61
  name: biome_recharge_io_herbier_benthos
  version: 1.0.0
  package_version: 0.0.0.9001
  created_at: 2025-01-30 16:23:38
  last_modified: 2025-01-30 16:23:38
  description: >
    Ce pipeline collecte des données sur l'herbier et le benthos du site de recharge IO, issues du laboratoire BIOME.

  metadata:
    source_name: "BIOME - IO Herbiers et Benthos"
    data_type: "CSV"
    file_size: "Inconnu"
    license: "Données en accès restreint"
    last_updated: "2023"
    geographic_coverage:
      region: "Site de recharge IO"
      bounding_box:
        - null
        - null
        - null
        - null
    temporal_coverage:
      start_date: "2023-01-01"
      end_date: "2023-12-31"
    variables:
      - herbiers
      - benthos
      - logbook
    data_quality: 
      - "Données validées par le laboratoire BIOME"

  bibliography:
    - "@TechReport{biome_io_2023,
        title = {Suivi des herbiers et du benthos au site de recharge IO},
        author = {{BIOME}},
        year = {2023},
        institution = {{Université Laval}},
      }"

  download:
    sources:
      - name: io_herbier_benthos
        description: Données sur les herbiers et le benthos du site IO
        source_type: "gcs"
        urls: "biome-resilience-cotiere"
        asset: "io_herbier_benthos/logbook/io_herbiers_benthos_2023.csv"
        credentials: "workspace/credentials/pof-stac-insileco-5d20b0cb59ef.json"

  processing:
    sources:
      - name: processing biome_recharge_io_herbier_benthos
        script: prc_biome_recharge_io_herbier_benthos
        input_files:
          - io_herbier_benthos
        output_files: 
          - biome_recharge_io_herbier_benthos_logbooks.csv

  output:
    output_dir: "workspace/data/harvested/recharge_io_herbier_benthos/"
    log_dir: "workspace/logs/"
    archive_raw: true
