pipeline:
  id: 66ac503f-ead2-46a4-afc9-e658e459efef
  name: zip_inventaire_marais_baie_mille_vaches
  version: 1.0.0
  package_version: 0.0.0.9001
  created_at: 2025-01-30 09:52:28
  last_modified: 2025-01-30 09:52:28
  description: |
    Ce pipeline collecte et traite des données sur la caractérisation des habitats 
    littoraux du marais de la Baie de Mille-Vaches, situé sur la rive nord de l’estuaire 
    maritime du Saint-Laurent. Le projet vise à générer des données écologiques de 
    référence pour évaluer l’état des marais littoraux dans le secteur de la Haute-Côte-Nord, 
    au Québec. Les données incluent des inventaires floristiques, ichtyologiques et benthiques, 
    ainsi que des mesures abiotiques.

  metadata:
    source_name: "Le marais de la Baie de Mille-Vaches - Caractérisation des habitats littoraux"
    data_type: "ZIP, PDF"
    file_size: "Inconnu"
    license: "Creative Commons Attribution 4.0 (CC-BY-4.0)"
    license_url: "https://creativecommons.org/licenses/by/4.0"
    last_updated: "2024-11-26"
    geographic_coverage:
      region: "Baie de Mille-Vaches, Québec"
      bounding_box:
        - -69.2568389  # Longitude min
        - 48.5193406   # Latitude min
        - -69.1483564  # Longitude max
        - 48.5855113   # Latitude max
    temporal_coverage:
      start_date: "2019-01-01"
      end_date: "2021-12-31"
    variables:
      - abiotic_factors (salinité, substrat, température)
      - fish_occurrences
      - benthic_occurrences
      - vegetation_occurrences
    data_quality:
      - "Noms taxonomiques validés via WoRMS."
      - "Échantillonnage et mesures normalisés selon les standards Darwin Core."

  bibliography:
    - "@Dataset{ziprne2024,
        title = {Baie de Mille-Vaches Marsh - Characterization of Important Coastal Habitats on the North Shore of the St. Lawrence Maritime Estuary},
        author = {{Comité ZIP de la Rive Nord de l’Estuaire}},
        year = {2024},
        publisher = {OGSL Catalogue},
        url = {https://doi.org/10.26071/ogsl-f10f496a-acf4}
      }"
    - "@TechReport{desrochers2023,
        title = {Rapport de caractérisation : Les marais littoraux d’importance à Longue-Rive},
        author = {Desrochers, V. and Quiec, F. and Marée, S. and D’Amours-Leclerc, F. and Maltais, M.K.},
        year = {2023},
        institution = {{Comité ZIP de la Rive Nord de l’Estuaire}},
        location = {Baie-Comeau, Québec},
        pages = {145 p + Annexes}
      }"
    - "@TechReport{morissette2012,
        title = {Caractérisation hydrogéomorphologique et sédimentologique de la plage de la Pointe-à-Boisvert, Longue-Rive, Haute-Côte-Nord},
        author = {Morissette, A. and Joyal, G.},
        year = {2012},
        institution = {{Université du Québec à Rimouski, Département de biologie, chimie et géographie}},
        location = {Baie-Comeau, Québec},
        pages = {86 p + Annexes}
      }"

  download:
    sources:
      - name: "Donnees echantillonnage"
        source_type: "http"
        urls: "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_f10f496a-acf4-4274-9c7b-7a005bcf54ed/DwC_zip_rne_marais_bmv_2019-2021.zip"
        output: "DwC_marais_bmv_2019-2021.zip"
        format: "zip"

      - name: "Rapport de caracterisation"
        source_type: "http"
        urls: "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_f10f496a-acf4-4274-9c7b-7a005bcf54ed/ziprne_portrait_ecogeomorphologique.pdf"
        output: "portrait_ecogeomorphologique.pdf"
        format: "pdf"

      - name: "Rapport hydrogeomorphologique et sedimentologique"
        source_type: "http"
        urls: "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_f10f496a-acf4-4274-9c7b-7a005bcf54ed/ziprne_caracterisation_hydrogeomorph_sedimentolo_plage_pointe_a_boisvert.pdf"
        output: "hydrogeomorph_sedimentologie_pointe_a_boisvert.pdf"
        format: "pdf"

  processing:
    sources:
      - name: process zip_inventaire_marais_baie_mille_vaches
        script: prc_zip_inventaire_marais_baie_mille_vaches
        input_files:
          - Donnees echantillonnage
        output_files:
          - marais_bmv_events.csv
          - marais_bmv_occurrences.csv
          - marais_bmv_abiotic.csv
          - marais_bmv_abundance.csv

  output:
    output_dir: "workspace/data/harvested/"
    log_dir: "workspace/logs/"
    archive_raw: true
