pipeline:
  id: 01fab37f-efbc-433d-8a08-d717200c0ff7
  name: zip_inventaire_marais_pointe_fortin
  version: 1.0.0
  package_version: 0.0.0.9001
  created_at: 2025-01-29 18:30:36
  last_modified: 2025-01-29 18:30:36
  description: |
    Ce pipeline collecte et traite des données sur la caractérisation des habitats
    littoraux du marais de la Pointe des Fortin, situé sur la rive nord de l’estuaire
    maritime du Saint-Laurent. Le projet vise à générer des données écologiques de
    référence pour évaluer l’état des marais littoraux dans le secteur de la Haute-Côte-Nord,
    au Québec. Les données incluent des inventaires floristiques, ichtyologiques et
    benthiques, ainsi que des mesures abiotiques.

  metadata:
    source_name: "Le marais de la Pointe des Fortin - Caractérisation des habitats littoraux"
    data_type: "CSV"
    file_size: "Inconnu"
    license: "Creative Commons Attribution 4.0 (CC-BY-4.0)"
    license_url: "https://creativecommons.org/licenses/by/4.0"
    last_updated: "2024-03-22"
    geographic_coverage:
      region: "Marais de la Pointe des Fortin, Québec"
      bounding_box:
        - -69.1176676  # Longitude min
        - 48.6185174   # Latitude min
        - -69.0334743  # Longitude max
        - 48.6747239   # Latitude max
    temporal_coverage:
      start_date: "2019-01-01"
      end_date: "2021-12-31"
    variables:
      - abiotic_factors (salinité, substrat, température)
      - fish_occurrences
      - benthic_occurrences
      - vegetation_occurrences
    data_quality:
      - "Noms taxonomiques validés via WoRMS."
      - "Échantillonnage et mesures normalisés selon les standards Darwin Core."

  bibliography:
    - "@Dataset{ziprne2022,
        title = {The Pointe des Fortin Marsh - Characterization of Important Coastal Habitats on the North Shore of the St. Lawrence Estuary},
        author = {{Comité ZIP de la Rive Nord de l’Estuaire}},
        year = {2022},
        publisher = {OGSL Catalogue},
        url = {https://doi.org/10.26071/ogsl-3b8c6d97-6eb8}
      }"

  download:
    sources:
      - name: "Evenements echantillonnage"
        source_type: "http"
        urls: "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_event_2019-2021.csv"
        output: "marais_pointe_fortin_events.csv"
        format: "csv"
      
      - name: "Mesures abiotiques"
        source_type: "http"
        urls: "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_event_emof_2019-2021.csv"
        output: "marais_pointe_fortin_abiotic.csv"
        format: "csv"

      - name: "Occurrences biologiques"
        source_type: "http"
        urls: "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_occurrence_2019-2021.csv"
        output: "marais_pointe_fortin_occurrences.csv"
        format: "csv"

      - name: "Donnees abondance"
        source_type: "http"
        urls: "https://catalogue.ogsl.ca/data/zip-rne/ca-cioos_3b8c6d97-6eb8-4e8d-9869-ccb2b9bab5f3/zip-rne_marais-pf_occurrence_emof_2019-2021.csv"
        output: "marais_pointe_fortin_abundance.csv"
        format: "csv"

  processing:
    sources:
      - name: process zip_inventaire_marais_pointe_fortin
        script: prc_zip_inventaire_marais_pointe_fortin
        input_files:
          - Evenements echantillonnage
          - Mesures abiotiques
          - Occurrences biologiques
          - Donnees abondance
        output_files:
          - marais_pointe_fortin_events.csv
          - marais_pointe_fortin_abiotic.csv
          - marais_pointe_fortin_occurrences.csv
          - marais_pointe_fortin_abundance.csv

  output:
    output_dir: "workspace/data/harvested/"
    log_dir: "workspace/logs/"
    archive_raw: true
