---
title: "Intégration des données"
---

L'objectif de cette section est de définir une organisation cohérente des données à travers des tables thématiques facilitant les analyses ultérieures. Les jeux de données considérés incluent des informations sur les stations d'échantillonnage, la biodiversité et les paramètres abiotiques, en plus des métadonnées et des références taxonomiques. La structure retenue permet une meilleure organisation et exploitation des informations issues de différentes campagnes d'échantillonnage. L'utilisation de tables relationnelles assure la traçabilité et l'interopérabilité des données, facilite les croisements entre paramètres biotiques et abiotiques, et améliore la reproductibilité des analyses. 

## Structure des données

L'intégration repose sur la création de plusieurs tables thématiques qui regroupent les informations selon leur nature : 

### Métadonnées (`metadata`)


::: {.callout-warning}
## Bonifier métadonnées

La table des métadonnées devra être élargie pour inclure des informations supplémentaires qui ne sont pas encore prises en compte. Toutefois, à ce stade du projet, la priorité est de poursuivre les prochaines étapes avant d’approfondir cet aspect. Une structuration plus détaillée des métadonnées sera envisagée dans une phase ultérieure afin d’améliorer la documentation et l’interopérabilité des données.
:::

| **Nom du champ**        | **Type de données** | **Description** |
|-------------------------|---------------------|-----------------|
| `project_id`           | `chr` (texte)       | Identifiant unique du projet associé aux données |
| `longitude_min`        | `num` (nombre)      | Coordonnée minimale en longitude du projet |
| `longitude_max`        | `num` (nombre)      | Coordonnée maximale en longitude du projet |
| `latitude_min`         | `num` (nombre)      | Coordonnée minimale en latitude du projet |
| `latitude_max`         | `num` (nombre)      | Coordonnée maximale en latitude du projet |
| `date_start`           | `POSIXct` (datetime) | Date et heure de début de la collecte des données |
| `date_end`             | `POSIXct` (datetime) | Date et heure de fin de la collecte des données |


### Événements (`events`)


| **Nom du champ**        | **Type de données** | **Description** |
|-------------------------|---------------------|-----------------|
| `project_id`           | `chr` (texte)       | Identifiant du projet associé à l'événement |
| `event_id`             | `chr` (texte)       | Identifiant unique de l'événement (Clé primaire) |
| `longitude`            | `num` (nombre)      | Coordonnée géographique (longitude) |
| `latitude`             | `num` (nombre)      | Coordonnée géographique (latitude) |
| `sampling_protocol`    | `chr` (texte)       | Méthode ou protocole utilisé pour l'échantillonnage |
| `geodetic_datum`       | `chr` (texte)       | Référence du système géodésique (ex: WGS84) |
| `remarks`              | `chr` (texte)       | Commentaires ou remarques sur l'événement |
| `depth`               | `num` (nombre)      | Profondeur en mètres (si applicable) |
| `event_date_start`     | `POSIXct` (datetime) | Date et heure de début de l'événement |
| `event_date_end`       | `POSIXct` (datetime) | Date et heure de fin de l'événement |
| `parent_event_id`      | `chr` (texte)       | Identifiant de l'événement parent (si applicable) |
| `site_id`             | `chr` (texte)       | Identifiant du site d'échantillonnage |
| `elevation`           | `num` (nombre)      | Élévation en mètres (si applicable) |
| `site_name`           | `chr` (texte)       | Nom du site d'échantillonnage |
| `sampling_effort`     | `chr` (texte)       | Effort d'échantillonnage décrit (si applicable) |
| `sample_size_value`   | `num` (nombre)      | Taille de l'échantillon prélevé (si applicable) |
| `sample_size_unit`    | `chr` (texte)       | Unité de mesure de la taille d'échantillon |


### Paramètres abiotiques (`abiotic`)


| **Nom du champ**               | **Type de données** | **Description** |
|--------------------------------|---------------------|-----------------|
| `event_id`                     | `chr` (texte)       | Identifiant unique de l'événement associé à la mesure |
| `measurement_category`         | `chr` (texte)       | Catégorie de la mesure (ex: Géologie, Qualité de l'eau, etc.) |
| `measurement_type`             | `chr` (texte)       | Type de mesure effectuée (ex: Intrusive, Métamorphique, Volcanique) |
| `measurement_type_description` | `chr` (texte)       | Description détaillée du type de mesure |
| `measurement_value`            | `chr` (texte)       | Valeur mesurée (ex: pourcentage, concentration, etc.) |
| `measurement_unit`             | `chr` (texte)       | Unité associée à la mesure (ex: %, mg/L, °C) |
| `measurement_method`           | `chr` (texte)       | Méthode utilisée pour effectuer la mesure |
| `measurement_remarks`          | `chr` (texte)       | Remarques supplémentaires sur la mesure (si applicable) |


### Taxonomie (`taxonomy`)

::: {.callout-warning}
## Consolider listes taxonomiques

La normalisation des données taxonomiques est un travail de grande ampleur qui devra être réalisé afin d’obtenir une liste unique d'espèces pour l’ensemble des projets et jeux de données intégrés. Cette tâche nécessitant un effort important, il a été décidé de ne pas approfondir cet aspect dans cette itération du projet. Par conséquent, lorsqu'on combine plusieurs projets pour des analyses intégrées, la biodiversité pourrait être surestimée en raison des variations de nomenclature des espèces, tandis que l’abondance, la biomasse et le recouvrement des espèces pourraient être sous-estimés faute de consolidation des données.
:::

| **Nom du champ**           | **Type de données** | **Description** |
|----------------------------|---------------------|-----------------|
| `species_id`              | `chr` (texte)       | Identifiant unique de l'espèce |
| `scientific_name`         | `chr` (texte)       | Nom scientifique de l'espèce |
| `scientific_name_id`      | `chr` (texte)       | Identifiant taxonomique dans la base de données spécifiée |
| `scientific_name_id_db`   | `chr` (texte)       | Base de données d'origine pour l'identifiant taxonomique (`itis`, `worms`, etc.) |
| `gbif_url`               | `glue` (texte)      | Lien vers la fiche de l'espèce sur GBIF (si disponible) |
| `taxon_rank`             | `chr` (texte)       | Rang taxonomique de l'espèce (ex: Espèce, Genre, Famille) |
| `kingdom`                | `chr` (texte)       | Règne de classification de l'espèce |
| `phylum`                 | `chr` (texte)       | Embranchement de l'espèce |
| `class`                  | `chr` (texte)       | Classe taxonomique de l'espèce |
| `order`                  | `chr` (texte)       | Ordre taxonomique de l'espèce |
| `family`                 | `chr` (texte)       | Famille taxonomique de l'espèce |
| `genus`                  | `chr` (texte)       | Genre taxonomique de l'espèce |
| `species`                | `chr` (texte)       | Nom complet de l'espèce (si applicable) |


### Biodiversité (`biodiversity`)

| **Nom du champ**         | **Type de données** | **Description** |
|--------------------------|---------------------|-----------------|
| `event_id`              | `chr` (texte)       | Identifiant unique de l'événement d'échantillonnage |
| `species_id`            | `chr` (texte)       | Identifiant unique de l'espèce associée à l'événement |
| `measurement_type`      | `chr` (texte)       | Type de mesure associée à l'espèce (`abundance`, `biomass`, `occurrence`) |
| `measurement_value`     | `chr` (texte)       | Valeur mesurée (ex: nombre d'individus, poids) |
| `measurement_unit`      | `chr` (texte)       | Unité de mesure correspondante (`n/m2`, `g/m2`, ou aucune unité) |

