project:
  type: book
  output-dir: ../../docs

book:
  title: Projet Résilience Côtière
  subtitle: Utilisation des communautés benthiques comme indicateurs de l’état écologique des écosystèmes côtiers du Saint-Laurent
  author: 
    - name: David Beauchesne
      degrees: PhD
    - name: Kevin Cazelles
      degrees: PhD
  chapters:
    - index.qmd
    - 1_research_compendium.qmd
    - 2_data.qmd
    - 3_integration.qmd
    - 4_indicateurs.qmd
    - 5_structure_communautes.qmd
    - 6_modelisation.qmd

bibliography: [ResilienceCotiere.bib, ../../workspace/bibliographies/data.bib]
csl: frontiers.csl

format:
  html:
    theme: cosmo
    toc-depth: 2

execute:
  echo: false
  warning: false
  error: false